site_name: demo-quarkus-app
site_description: This is backend Quarkus Application that handles REST APIs for demo purposes.
repo_url: https://github.com/janus-idp-demo/demo-quarkus-app
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# Note for content editors, edit only the section below
nav:
  - Onboard a developer to OpenShift: onboard-openshift.md
  - Application Migration:
      - Migration Process Overview: application-migration/migration-process-overview.md
      - Migration Process Steps: application-migration/migration-process-steps.md
      - Learning Path for Developers: application-migration/learning-path-for-developers.md
